---
- name: Install Kubectl
  apt:
    name:
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name:
      - kubelet 
      - kubeadm 
      - kubectl
    state: present
    update_cache: yes


#After this step it's necessary to insert rancher credentials in ~/.kube/config in the rancher host